branches:
  only:
  - master

language: cpp

os:
 - linux
 - osx

compiler:
  - gcc
  - clang

jobs:
  include:
    - os: windows

addons:
  apt:
    packages:
    - xorg-dev  

before_script:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install -y xpra xserver-xorg-video-dummy freeglut3-dev; fi
  - cd test 
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug -DPOLYSCOPE_BACKEND_OPENGL3_GLFW=ON -DPOLYSCOPE_BACKEND_OPENGL_MOCK=ON ..

script: 
  - |
    if [ "$TRAVIS_OS_NAME" = "linux" ]; then 
      make 
      ./bin/polyscope-test --gtest_catch_exceptions=0 backend=openGL_mock
    fi
  - |
    if [ "$TRAVIS_OS_NAME" = "osx" ]; then 
      make 
      ./bin/polyscope-test --gtest_catch_exceptions=0 backend=openGL_mock
    fi
  - |
    if [ "$TRAVIS_OS_NAME" = "windows" ]; then 
      cmake --build "."
      ls
      ./bin/Debug/polyscope-test.exe --gtest_catch_exceptions=0 backend=openGL_mock
    fi
